# Example secrets configuration for Streamlit Cloud
# Copy this content to your Streamlit Cloud App Settings > Secrets

# Database Configuration
DB_TYPE = "sqlite"
DB_PATH = "litgrid_local.db"

# Application Security - CHANGE THESE VALUES!
SECRET_KEY = "your-super-secret-key-change-this-in-production-make-it-long-and-random"
ENCRYPTION_KEY = "your-32-character-encryption-key"

# Application Settings
APP_NAME = "LitGrid"
APP_VERSION = "4.0"
DEBUG = false

# Admin Credentials (Optional)
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "secure-password-here"

# Email Configuration (Optional - for notifications)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "your-email@gmail.com"
SMTP_PASSWORD = "your-gmail-app-password"
SMTP_FROM_EMAIL = "noreply@litgrid.com"